language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - jruby

jdk:
  - oraclejdk8

env:
  global:
    - TRAVIS_NODE_VERSION="4.0"
  matrix:
    - ROUGE="~> 1.8"
    - ROUGE="~> 2.0"

matrix:
  allow_failures:
    - rvm: jruby

before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra tidy
  - gem install rake --version 10.5.0
  - gem install minitest coderay stringex ritex
  - gem install rouge --version "${ROUGE}"
  - gem install prawn prawn-table
  - (ruby --version | grep jruby) || gem install itextomml
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install mathjax-node@"<1.0" cssstyle

script: ruby -rubygems -Ilib:test test/test_*
